repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: terraform_fmt
    -   id: terraform_docs
    -   id: terraform_tflint
    -   id: terraform_validate
    -   id: terraform_tfsec
    files: '\.tf$
